### ISSUE TITLE
consider renaming "cloudml" parameter to "config"

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#104]
Now that we've eliminated the gcloud parameter as well as the previously used "config" parameter I think it would be more clear to name the "cloudml" parameter "config" (as that matches what's used on the gcloud command line).

@javierluraschi What do you think? I'm happy to make this change if you agree.

**Comment by jjallaire** [comment]
So this invocation:

```r
cloudml_train("mnist_mlp.R", cloudml = "tuning.yml")
```

Would become this:

```r
cloudml_train("mnist_mlp.R", config = "tuning.yml")
```

Which I think reads more naturally.

**Comment by javierluraschi** [comment]
@jjallaire the rename makes a lot of sense.

**Comment by jjallaire** [comment]
Implemented
