### ISSUE TITLE
job_trials returns data frame with factors rather than numeric values

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#105]
The data frame returned by `job_trials()` is processing the data as strings (which then become factors):

```
'data.frame':	10 obs. of  5 variables:
 $ finalMetric.objectiveValue: num  0.974 0.973 0.973 0.973 0.973 ...
 $ finalMetric.trainingStep  : Factor w/ 1 level "19": 1 1 1 1 1 1 1 1 1 1
 $ hyperparameters.dropout1  : Factor w/ 10 levels "0.2011326172916916",..: 1 2 3 4 5 6 7 8 9 10
 $ hyperparameters.dropout2  : Factor w/ 10 levels "0.32774705750441724",..: 1 2 3 4 5 6 7 8 9 10
 $ trialId                   : Factor w/ 10 levels "10","3","6","7",..: 1 2 3 4 5 6 7 8 9 10
```

We need to convert the columns to their appropriate numeric types.

**Comment by jjallaire** [comment]
@javierluraschi If you could take a look at this one right away that would be great (it's our only blocker to release of the package)

**Comment by javierluraschi** [comment]
I'm getting a different result with the `examples/mnist/` tunning run...

```
> job_trials("cloudml_2018_01_05_222054521")
         dropout.rate trialId
1 0.45310151480049365       2
2 0.48219358982993954       1
```

trying `examples/keras`...

**Comment by jjallaire** [comment]
Check the actual types of the columns (they may appear to be numeric from their display but they are character/factor in the data frame)

**Comment by javierluraschi** [comment]
They seem to be numeric...

```
> df <- job_trials("cloudml_2018_01_05_222054521")
> df$dropout.rate
[1] 0.45310151480049365 0.48219358982993954
Levels: 0.45310151480049365 0.48219358982993954
> typeof(df$dropout.rate)
[1] "integer"
> typeof(df$trialId)
[1] "integer"
```

I'm trying to get the `mnist_mlp.R` with the `tuning.yml` file to complete, but has been running for a while...

<img width="1114" alt="screen shot 2018-01-08 at 3 39 13 pm" src="https://user-images.githubusercontent.com/3478847/34697932-3b8cb7a4-f48a-11e7-8b7c-f649baf6ac28.png">

I'm trying a GPU instance now...

**Comment by javierluraschi** [comment]
Just finished training `mnist_mlp.R`...

```r
job_trials("cloudml_2018_01_08_224357100")
   finalMetric.objectiveValue finalMetric.trainingStep hyperparameters.dropout1 hyperparameters.dropout2 trialId
1                    0.973854                       19        0.231957378172672      0.32137458951239611       7
2                    0.973708                       19      0.33738305074626346      0.37709752765610249       2
3                    0.973229                       19      0.48864698388900124      0.20707561956482215       1
4                    0.973042                       19      0.59976599920557128      0.10370792198585282       6
5                    0.972833                       19        0.366499815048923      0.41615197458722941       5
6                    0.972729                       19      0.41293948551197446      0.10197616506029067       9
7                    0.972479                       19      0.20755950441509025      0.20996598005982961       8
8                    0.972229                       19      0.39221210407509677      0.32550206717332386       4
9                    0.971604                       19      0.59965713418956357      0.29417303332475742      10
10                   0.971417                       19      0.20920643639786116      0.48688580001181059       3
```

```
x <- job_trials("cloudml_2018_01_08_224357100")
typeof(x$finalMetric.objectiveValue)
[1] "double"
```

Do you have a repro you can share to take a closer look? Thanks!

**Comment by javierluraschi** [comment]
Sent PR with fix.

**Comment by medewitt** [comment]
I think this fix might be causing another issue.  I am training a model over different activation functions. The returned job_trials() dataframe structure has number as type for these character values so it drops them as NA when it coerces them to numeric.

![image](https://user-images.githubusercontent.com/25038837/35570059-08ee094c-059c-11e8-8b04-84450bc3dc8e.png)

**Comment by jjallaire** [comment]
@javierluraschi Could you take a look at this one right away? (I want to make sure we resolve any issues here before the conference)

**Comment by javierluraschi** [comment]
@medewitt thanks you, a fix was provided here: https://github.com/rstudio/cloudml/pull/118

Please retry after running:

```r
devtools::install_github("rstudio/cloudml")
```
