### ISSUE TITLE
add documentation on appropriate hyperparameterMetricTag

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#106]
Our tuning vignette uses a Keras job to demonstrate the use of hyperparameterMetricTag. We should also document correct usage for tfestimators and core API training jobs (drawing code from your existing core mnist example). Placeholder in tuning vignette is here: https://github.com/rstudio/cloudml/blob/master/vignettes/tuning.Rmd#optimization-metrics

**Comment by javierluraschi** [comment]
See https://github.com/rstudio/cloudml/pull/110
