### ISSUE TITLE
flags passed by hyperparameter tuning don't propagate all the way to the R script 

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#107]
When I run a tuning job and then look at the job output (via `view_run()` on individual trials) I don't see distinct FLAGS based on what the hyperparameter tuning supervisor should be passing. i.e. if I execute the following local command line:

```
Rscript mnist_mlp.R --dropout1=0.7 --dropout2=0.65
```

The dropout1 and dropout2 parameters get propagated to FLAGS and I see them reported as such in `view_run()`. Note that you can also print the `FLAGS` object within a training script to easily inspect what the values were for a job (the Output tab of view_run will show this output).

Without the flags being propagated tuning won't actually do what it's supposed to.

**Comment by javierluraschi** [comment]
@jjallaire What would be the repro on this one? I created a `flags_test.R` file:

```r
library(keras)

FLAGS <- flags(
  flag_integer("test_flag", 123)
)

message("Flag:", FLAGS$test_flag)
```

then run:

```
cloudml_train("flags_test.R", flags = list(test_flag = 456))
```

and got:

<img width="1095" alt="screen shot 2018-01-08 at 3 11 46 pm" src="https://user-images.githubusercontent.com/3478847/34697074-44e12118-f486-11e7-92f9-fbce413b388d.png">

which looks correct to me.

**Comment by jjallaire** [comment]
My repro was looking at the flags reported in the `view_run()` report (which could have some reason for varying that I'm not considering). What do you see when you `view_run()`?

**Comment by javierluraschi** [comment]
I do get this flag in `tfrun::view_run()` as well:

<img width="1098" alt="screen shot 2018-01-08 at 3 36 30 pm" src="https://user-images.githubusercontent.com/3478847/34697821-c084cdc6-f489-11e7-8ea9-fe7d9fd97802.png">

**Comment by jjallaire** [comment]
The issue isn't with vanilla calls to `cloudml_train()`, it's with hyperparameter tuning in particular. I've changed the keras example to use only 2 trials and to print the FLAGS. When executing this:

```r
cloudml_train("mnist_mlp.R", config = "tuning.yml")
```

I do not see the FLAGS being propagated to the tuning jobs. I do however see this:

```
Command ['Rscript', '/root/.local/lib/python2.7/site-packages/cloudml-model/cloudml/deploy.R', '--args', '--dropout1', '0.30783999058503619', '--job-dir', 'gs://cedar-card-791/r-cloudml/staging/1'] ran successfully.
```

Which to me seems like it should be propagating but when you look at what gets printed in FLAGS and what gets written to tfruns.d/flags.json the values are still at the defaults.

**Comment by javierluraschi** [comment]
I see, I'm pretty sure this was working, but yes I can repro this now for tuning jobs. I see the following in the logs:

```
master-replica-0
Command args: /usr/lib/R/bin/exec/R, --slave, --no-restore, --file=/root/.local/lib/python2.7/site-packages/cloudml-model/cloudml/deploy.R, --args, --args, --num-epochs, 5, --job-dir, gs://rstudio-cloudml/r-cloudml/staging/2
```

We probably need to fix the duplicate `--args` in the python script that loads the actual r script, taking a look...
