### ISSUE TITLE
JSON body for cloudml_predict function

### ISSUE THREAD

**Issue by mwhitaker** [rstudio/cloudml#112]
I worked through the [deployment example](https://tensorflow.rstudio.com/tools/cloudml/articles/deployment.html#prediction) which works great. Once the model is hosted and serving it would be useful (to me at least) if I could see the equivalent [JSON representation](https://cloud.google.com/ml-engine/docs/v1/predict-request) so I can quickly see how to get predictions using other services without having to translate R lists to JSON.

Perhaps a verbose option (as found in httr) could be added to the `cloudml_predict(..., verbose=TRUE)` function that prints out the request when you call that function?

Thank you for a great package and I hope it's OK to post a feature idea as an issue.

Michael

**Comment by jjallaire** [comment]
You can also use the `serve_savedmodel()` function from the **tfdeploy** package (docs here: https://rstudio.github.io/tfdeploy/) which will render a web page describing the JSON API for the model.

@javierluraschi +1 on having a `verbose=TRUE` that shows the JSON.

**Comment by mwhitaker** [comment]
wow - thank you for pointing me to tfdeploy!

**Comment by javierluraschi** [comment]
Thanks @mwhitaker,  a`verbose` was parameter added to `cloudml_predict()`, you can install using:

```r
devtools::install_github("rstudio/cloudml")
```

**Comment by mwhitaker** [comment]
Thank you! Very helpful. Now I can just copy and paste the prediction request into a json file and be confident about posting the payload in the right format.

Just tested it with the gcloud CLI and works like a charm.

![cloudml_predict_verbose](https://user-images.githubusercontent.com/3980239/35938199-41d4466a-0bfd-11e8-9fa2-e5daea5211d1.png)
