### ISSUE TITLE
failed to find gcloud binary on windows machines

### ISSUE THREAD

**Issue by medewitt** [rstudio/cloudml#115]
Hi team,

Love the package but I am having a problem deploying on my windows 10 machine. I have gone through the install path

library(cloudml)
install_gcloud()

I run through the install process and set the paths as follows:

C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin
C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk

What am I missing? I still get the _Error in gcloud_binary() : failed to find 'gcloud' binary_ message

**Comment by jjallaire** [comment]
@javierluraschi Could you take a look at this?

**Comment by jjallaire** [comment]
Looking at the code I think you need to accept the default of a per-user installation in order for us to find the gcloud binary.

@javierluraschi I think we should also be able to locate it if the user chooses a system install.

If you have strong reasons for using a system install I think if you add the directory to your system PATH we will find it.

There is also an option to set the  `GCLOUD_BINARY_PATH` environment variable or the `gcloud.binary.path` R option to the location of your gcloud binary, but as things currently stand you would also need to set a `GSUTIL_BINARY_PATH` environment variable so it's probably easier to just set the system PATH.

**Comment by javierluraschi** [comment]
Issue is fixed now, please update using:

```
devtools::install_github("rstudio/cloudml")
```

**Comment by aks10000** [comment]
![image](https://user-images.githubusercontent.com/22571800/57457358-02890480-728d-11e9-862f-313a7248a15f.png)
 Any solution for this
