### ISSUE TITLE
consider using RStudio terminals for some commands

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#12]
For example, when kicking off a training run, it might be useful to run that as part of an RStudio terminal (so the R session remains unblocked, but logs are still streamed to a window that can be easily viewed as they come in).

We might also want to use `processx` rather than `system2` in launching these processes (especially for processes we want to run asynchronously)

**Comment by javierluraschi** [comment]
`processx -> system2`, already implemented, same for logs streaming.
