### ISSUE TITLE
Community report that `gsutil` can't find binary

### ISSUE THREAD

**Issue by andrie** [rstudio/cloudml#122]
Original report at https://community.rstudio.com/t/cloudml-package-error-in-gsutil-binary-failed-to-find-gsutil-binary/4950

```r
cloudml:::gsutil_binary()
Error in gsutil_binary() : failed to find 'gsutil' binary
```

I'm unable to reproduce on my machine

**Comment by jjallaire** [comment]
@javierluraschi Could you look into this one further?

**Comment by javierluraschi** [comment]
Yes, planning to make some time this week to look at this one. We think that conda + cloudml is the culprit here.

**Comment by rtjohn** [comment]
I think my issue may be related?  This is the code I'm running:

```
# Installing Google CloudML Tools
devtools::install_github("rstudio/cloudml")
library(cloudml)
gcloud_install()
```

Here is the output:

```
> # Installing Google CloudML Tools
> devtools::install_github("rstudio/cloudml")
Downloading GitHub repo rstudio/cloudml@master
from URL https://api.github.com/repos/rstudio/cloudml/zipball/master
Installing cloudml
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wy/lp95hpnn5rzfv604469d9r3w0000gn/T/Rtmp3QDaGE/devtools50c2c84fede/rstudio-cloudml-38a2da4'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘cloudml’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (cloudml)
Reloading installed cloudml

> library(cloudml)

> gcloud_install()
Downloading Google Cloud SDK...
trying URL 'https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash'
Content type 'application/octet-stream' length 6006 bytes
==================================================
downloaded 6006 bytes

Installation of the Google Cloud SDK will continue in a terminal [OK]: y
Error in gcloud_binary() : failed to find 'gcloud' binary
```

This is on a Mac running 10.13.3
Rstudio v 1.1.423
R v 3.4.3

**Comment by dfalbel** [comment]
On MacOS there are permission problems when installing gcloud. I think this is related: https://stackoverflow.com/a/21237848/3297472

**Comment by sniffadog001** [comment]
I am having this same problem today.  Running this on Google Cloud Platform Vm instance of Rstudio.

# Installing Google CloudML Tools
devtools::install_github("rstudio/cloudml")
library(cloudml)
gcloud_install()

And still getting 

cloudml:::gsutil_binary()
Error in cloudml:::gsutil_binary() : failed to find 'gsutil' binary

**Comment by dohanaga** [comment]
I am having another type of error in the terminal :
ou must log in to continue. Would you like to log in (Y/n)?  Y

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&code_challenge=vQbMlRJC5o8NfP9Ojxz-_8AcTbCbAUjghajlOcEuib8&code_challenge_method=S256&access_type=offline&response_type=code&prompt=select_account
 Cannot open display: .

Do I have to enable something from my google account to allow the access of rstudio to google ? what am I missing here?
