### ISSUE TITLE
error: can't copy 'cloudml-model/cloudml': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by mpelath** [rstudio/cloudml#125]
About a week and a half ago, I had the introductory IMDB example from Deep Learning with R running successfully, both locally on my Mac, and via cloudml.  This weekend, it stopped working via cloudml, throwing multiple (presumably related) errors.  Lengthy output to the shell is attached.  I raised this issue on SO, because I wasn't even sure whether this was a configuration problem, a cloudml problem, or a gcloud problem (or something else), but no responses.

The only thing that I'm reasonably sure changed in between is that something was updated, I _think_ the Google Cloud SDK, but that could be a red herring.  Uninstalling and reinstalling cloudml and the SDK didn't help.

[terminal_log.txt](https://github.com/rstudio/cloudml/files/1746567/terminal_log.txt)

**Comment by jjallaire** [comment]
@javierluraschi Could you take a look at this?

**Comment by javierluraschi** [comment]
Fixed by https://github.com/rstudio/cloudml/pull/129, yes, seems like debian machines got introduced and changes to python required setup changes.
