### ISSUE TITLE
Is there a way to train the number of hidden layers?

### ISSUE THREAD

**Issue by tianwei-zhang** [rstudio/cloudml#131]
The documentation at google cloud claims that hyper-parameter tuning could train the number of hidden layers (in addition to the number of units in a layer). But I cannot find any example. Is there a way to specify it in the training flag? Or do we have to submit multiple jobs with different number of layers? 

Thank you

**Comment by jjallaire** [comment]
You just need to make the number of hidden layers the result of one of your FLAGS. For example, write a loop that drives the number of hidden layers:

```r
FLAGS <- flags(
  flag_integer("hidden_layers", 2)
)

model <- keras_model_sequential()
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) 

for (i in 1:FLAGS$hidden_layers)
  model %>% layer_dense(units = 128, activation = 'relu')

model %>% 
  layer_dense(units = 10, activation = 'softmax')
```

**Comment by tianwei-zhang** [comment]
Thank you!
