### ISSUE TITLE
Package Dependencies in Google Environment

### ISSUE THREAD

**Issue by mgahan** [rstudio/cloudml#132]
This is an awesome package! Thanks so much to the people involved. I do have a question about package dependencies. I notice when I submit a training script, some packages are available in the the Google environment (`dplyr`), but others are not available (`data.table`). Is there a way to add packages to the new environment.

I notice the following doesn't really seem to work:

```
if (!require("data.table")) { install.packages("data.table") }
```

**Comment by mgahan** [comment]
When I added a `library(data.table)` to my training script I received this error:

```
> cloudml_train("mnist_mlp.R", master_type = "standard_gpu")
Submitting training job to CloudML...
Error: Unable to retrieve package records for the following packages:
- 'data.table'
```

But this was after I had already trained and tested the script without bringing in this extra library. Would it be a cache issue?

**Comment by jjallaire** [comment]
Did you install data.table from CRAN? If not then packrat isn’t able to
properly add it to the list of dependencies.

**Comment by mgahan** [comment]
That's it! I just removed the dev package and install the CRAN package and it seems to be working. Thanks @jjallaire
