### ISSUE TITLE
terminating API's on GCP using R function

### ISSUE THREAD

**Issue by longhowlam** [rstudio/cloudml#136]
Hi,

I have been experimenting with R cloudml, it's fantastic. I was wondering if it is possible in the R script to close / terminate the API on GCP so that you stop incurring charges.

Regards,
Longhow

**Comment by jjallaire** [comment]
You can use the `job_cancel()` function to cancel a running job: https://tensorflow.rstudio.com/tools/cloudml/reference/job_cancel.html

**Comment by longhowlam** [comment]
OK, thanks. I am not so familiar with the GCP, but if have submitted a job with

`job <- cloudml_train("mnist_mlp.R")
`

and the job has finished normally, then there is no need to terminate machines or API's on GCP? You will stop incurring charges?

Regards,
Longhow

**Comment by jjallaire** [comment]
Yes, correct. When the job finishes you stop incurring charges.
