### ISSUE TITLE
provide install_gcloud_sdk() helper

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#14]
Automate this so users don't have to go through the fuss of doing it themselves (as much as possible).

**Comment by kevinushey** [comment]
We should also provide documentation as to how a Google Cloud project can be set up for use with `cloudml`. We would likely want to link + build on the documentation at https://cloud.google.com/ml-engine/docs/quickstarts/command-line.

**Comment by javierluraschi** [comment]
We have now `gcloud_install`.
