### ISSUE TITLE
Errors and note on large files

### ISSUE THREAD

**Issue by Vidaringa** [rstudio/cloudml#146]
Hello and thank you for a great package.

I'm having a trouble when submitting a job. When viewing the log I see these three error message:
![image](https://user-images.githubusercontent.com/20194883/38836930-9724395c-41bf-11e8-816c-5cc11d2f548f.png)

Further down the log I get these messages (my dataset is 40MB csv file):
![image](https://user-images.githubusercontent.com/20194883/38837005-e85c4d14-41bf-11e8-8c08-c36e08611dbd.png)
After these messages the job hangs for 22 minutes.

The third issue is then related to the training itself. All the epochs takes around 120 sec, which is the same amount of time as on an old macbook air, even though I submitted the job using "standard-gpu".
What then happens is that epoch 11 actually takes 17 minutes according to the log. 
![image](https://user-images.githubusercontent.com/20194883/38837127-54ed1ab2-41c0-11e8-8492-6e1fea0e665d.png)

The job takes 48 minutes to complete.

Any idea of what's going on?

**Comment by jjallaire** [comment]
@javierluraschi note that there was a 17 minute delay between epochs here! To me it seems like something is going on in the back end that stops computation. Perhaps the folks from Google Cloud have some ideas what this might be?

**Comment by Vidaringa** [comment]
I'm still having those issues. Is it possible to get update/information if someone is looking into this?

**Comment by javierluraschi** [comment]
Had an email exchange with the Google CloudML team, they don't believe this is caused in CloudMLs infrastructure since hangs and errors (say the machine reboots, etc.) should log the event as their infrastructure provisions a new GPU, etc. So likely to be in tensorflow or the `cloudml` package itself.

@Vidaringa do you have a consisten script to reproduce this behavior you can share?

In any case, I'm planning to try to reproduce this one with a few jobs that make use of large datasets and report back if I spot the hang.

**Comment by Vidaringa** [comment]
I haven't been able to work on the problem for a while. In the meantime I upgraded R to 3.5.0 and now I can't replicate the problem since I'm getting another problem:

curl: (22) The requested URL returned error: 502 Bad Gateway
Error in download.file(url, destfile, method, mode = "wb", ...) :
Warning in download.packages(name, destdir = destdir, repos = repos, type = type,  :
download of package 'lamW' failed

**Comment by Vidaringa** [comment]
I did some changes to the code and it's working perfectly now.

Thank you for your help.

**Comment by javierluraschi** [comment]
Great, feel free to open a new github issue if this issue comes back.
