### ISSUE TITLE
Parse config.yml for runtimeVersion

### ISSUE THREAD

**Issue by andrie** [rstudio/cloudml#148]
The Cloud ML version is hard coded in `cloudml_train()` to be 1.6  (see #147).

The CLI allows for passing in `--runtime-version` ([docs](https://cloud.google.com/sdk/gcloud/reference/ml-engine/jobs/submit/training)) but you can also specify this from a [config file](https://cloud.google.com/ml-engine/reference/rest/v1/projects.jobs).

The docs says:

> If an option is specified both in the configuration file and via command line arguments, the command line arguments override the configuration file.

But right now we pass the version in the CLI argument, and there is no way to update this using the config.

**Comment by javierluraschi** [comment]
@andrie, let me know if I'm missing to understand something here, this works for me:

```yml
# config.yml
trainingInput:
  runtimeVersion: "1.4"
```

```r
# hello.R
message("Hello World")
```

Then from R I run:

```r
cloudml::cloudml_train("hello.R", config = "config.yml")
```

Both, status page and logs show `cloudml` using version `1.4` of the runtime...

<img width="1029" alt="screen shot 2018-05-22 at 3 52 56 pm" src="https://user-images.githubusercontent.com/3478847/40394475-85e72ed0-5dd8-11e8-8250-0d09deb94111.png">

<img width="1128" alt="screen shot 2018-05-22 at 3 54 37 pm" src="https://user-images.githubusercontent.com/3478847/40394476-85fc6bf6-5dd8-11e8-850f-ea0cabd5c28a.png">

**Comment by andrie** [comment]
That's good to know.  I can't remember what I tried.  Perhaps I didn't use quotes for the version number.

Perhaps we can include this how-to in the documentation somewhere?

**Comment by javierluraschi** [comment]
Just noticed that this is actually available in the docs:

https://tensorflow.rstudio.com/tools/cloudml/articles/training.html#training-configuration

<img width="840" alt="screen shot 2018-05-29 at 5 57 43 pm" src="https://user-images.githubusercontent.com/3478847/40692983-d4f20a0e-6369-11e8-8b41-93d5624706f2.png">

However, would make sense to update the runtime version to 1.4.
