### ISSUE TITLE
Keras example not working

### ISSUE THREAD

**Issue by avidalfinsa** [rstudio/cloudml#149]
Hi,
I was trying to execute the Keras example but it doesn't work.

In RStudio it seems to fail when it is installing packages: 

![image](https://user-images.githubusercontent.com/38490099/39746517-d0861908-52aa-11e8-8694-19bfc353e531.png)

But in the GC Logs, the training process continue and it fails at the end when try to get the results.

![image](https://user-images.githubusercontent.com/38490099/39746365-6da68804-52aa-11e8-9a69-b5f6d2c2e7bf.png)

I already try to rerun the example deleting r-cloudml on GCS but the problem persists. Any sugestion?

Thanks

**Comment by andrie** [comment]
Thank you for the report, @avidalfinsa.

Can you please provide more information so it's easier to reproduce and provide feedback?


* What is your version of the `cloudml` package?
* Which `keras` example do you refer to?
* Please post more of the logs, so we can see the line that actually contains the error code.  If possible, post this as text (not a screen shot), so it's easier to parse the error messages.
* What is your session information (use `sessioninfo::session_info()`)?

Does the problem persist when you use the lastest version of `cloudml` from github?

**Comment by andrie** [comment]
I spoke to @avidalfinsa while at Strata last week.

The main problem is that the `tuning.yml` file in the `keras` example is missing an argument. 

This is the repro:

```r
library(here)
library(cloudml)

cml <- system.file("examples/keras", package = "cloudml")
file.copy(list.files(cml, full.names = TRUE), to = ".", overwrite = TRUE)
list.files()

setwd(here("keras"))
cloudml_train("mnist_mlp.R", config = "tuning.yml", collect = TRUE)
setwd(here())
```

And the error message is:

```
[errmsg]
ERROR: (gcloud.ml-engine.jobs.submit.training) INVALID_ARGUMENT: Field: hyperparameters.max_parallel_trials Error: The number of max hyperparameter parallel trials must be set.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: The number of max hyperparameter parallel trials must be set.
    field: hyperparameters.max_parallel_trials
```

I will push a PR to fix this imminently.

**Comment by javierluraschi** [comment]
Great, thanks @andrie, fixed now with your PR.
