### ISSUE TITLE
gcloud_exec() on Windows throws errors

### ISSUE THREAD

**Issue by andrie** [rstudio/cloudml#153]
Related to #152 (where I tried to update the gcloud SDK using the terminal), I attempted the same action using the `gcloud_exec()` function:

```r
gcloud_exec("components update")
```

```
Error: ERROR: gcloud invocation failed [exit status 1]

[command]
cmd /c C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd components update

[output]


[errmsg]
'C:\Users\apdev\AppData\Local\Google\Cloud' is not recognized as an internal or external command,
operable program or batch file.
```

And:

```r
gcloud_exec("gcloud components update")
```

```
Error: ERROR: gcloud invocation failed [exit status 1]

[command]
cmd /c C:\Users\apdev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd gcloud components update

[output]


[errmsg]
'C:\Users\apdev\AppData\Local\Google\Cloud' is not recognized as an internal or external command,
operable program or batch file.
```

Session info:

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-05-24                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       source                          
 assertthat    0.2.0   2017-04-11 CRAN (R 3.4.0)                  
 backports     1.1.2   2017-12-13 CRAN (R 3.4.3)                  
 base64enc     0.1-3   2015-07-28 CRAN (R 3.4.0)                  
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.2)                  
 cloudml     * 0.5     2018-05-23 Github (rstudio/cloudml@4ce808c)
 crayon        1.3.4   2017-09-16 CRAN (R 3.4.2)                  
 debugme       1.1.0   2017-10-22 CRAN (R 3.4.2)                  
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)                  
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)                  
 packrat       0.4.9-2 2018-04-20 CRAN (R 3.4.4)                  
 processx      3.1.0   2018-05-15 CRAN (R 3.4.4)                  
 R6            2.2.2   2017-06-17 CRAN (R 3.4.1)                  
 rprojroot     1.3-2   2018-01-03 CRAN (R 3.4.3)                  
 rstudioapi    0.7     2017-09-07 CRAN (R 3.4.1)                  
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.3)                  
 tfruns      * 1.3     2018-04-10 Github (rstudio/tfruns@282de31) 
 whisker       0.3-2   2013-04-28 CRAN (R 3.4.0)                  
 withr         2.1.2   2018-03-15 CRAN (R 3.4.4)                  
 yaml          2.1.19  2018-05-01 CRAN (R 3.4.4) 
```

**Comment by jjallaire** [comment]
@javierluraschi This looks like a quoting issue to me (this is being identified as the binary: C:\Users\apdev\AppData\Local\Google\Cloud)

**Comment by javierluraschi** [comment]
@andrie currently, we would have to run this instead as:

```r
gcloud_exec("components", "update")
```

That will trigger the command in Windows; however, to print the result and inspect this further you can run:

```r
cat(gcloud_exec("components", "update")$stdout)
```

```bash
Error: ERROR: gcloud invocation failed [exit status 1]

[command]
cmd /c C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd components update

[output]


[errmsg]

ERROR: Cannot use bundled Python installation to update Cloud SDK in
non-interactive mode. Please run again in interactive mode.



If you really want to run in non-interactive mode, please run the
following command before re-running this one:



  FOR /F "delims=" %i in ( '""C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd"" components copy-bundled-python'
  ) DO (
    SET CLOUDSDK_PYTHON=%i
  )

(Substitute `%%i` for `%i` if in a .bat script.)
```

One improvement we can make is to set `echo = TRUE` by default.

**Comment by javierluraschi** [comment]
I'm going to close this... the only other fix we could do would be to support interactive mode in `gcloud_exec()` but that would basically look like implementing a terminal.

**Comment by DavidArenburg** [comment]
@javierluraschi Can't we just quote the path Cloud SDK in case it's a Windows OS? I can't find the function that generates that path but it sounds like a very simple fix. If it's on Google side, we can open a PR there.

**Comment by dsaada** [comment]
I use cloudml, i suspect that when i use huge amount of data, the system is down, i try with the same local dataset with size/100, that work, any help?


> cloudml_train("train.R")
Submitting training job to CloudML...
Error: ERROR: gcloud invocation failed [exit status 1]

[command]
cmd /c C:\Users\saadad\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd --account david_saada@carrefour.com --project parcours-octroi-clients ai-platform jobs submit training cloudml_2019_11_28_083125552 --job-dir=gs://parcours-octroi-clients/r-cloudml/staging --package-path=cloudml-model --module-name=cloudml-model.cloudml.deploy --runtime-version=1.9 --region=us-central1 --config=cloudml-model/cloudml.yml -- Rscript

[output]


[errmsg]
ERROR: (gcloud.ai-platform.jobs.submit.training) Packaging of user Python code failed with message:

Traceback (most recent call last):
  File "C:\Users\saadad\AppData\Local\Temp\Rtmpkr625I\cloudml-deploy-tensor_flow_4-39703c8c48c\setup.py", line 8, in <module>
    import yaml
ImportError: No module named yaml


Try manually building your Python code by running:
  $ python setup.py sdist
and providing the output via the `--packages` flag (for example, `--pac

**Comment by Weblogon** [comment]
> I use cloudml, i suspect that when i use huge amount of data, the system is down, i try with the same local dataset with size/100, that work, any help?
> 
> > cloudml_train("train.R")
> > Submitting training job to CloudML...
> > Error: ERROR: gcloud invocation failed [exit status 1]
> 
> [command] cmd /c C:\Users\saadad\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd --account xxx --project xxx ai-platform jobs submit training cloudml_2019_11_28_083125552 --job-dir=gs://xxx/r-cloudml/staging --package-path=cloudml-model --module-name=cloudml-model.cloudml.deploy --runtime-version=1.9 --region=us-central1 --config=cloudml-model/cloudml.yml -- Rscript
> 
> [output]
> 
> [errmsg] ERROR: (gcloud.ai-platform.jobs.submit.training) Packaging of user Python code failed with message:
> 
> Traceback (most recent call last): File "C:\Users\saadad\AppData\Local\Temp\Rtmpkr625I\cloudml-deploy-tensor_flow_4-39703c8c48c\setup.py", line 8, in import yaml ImportError: No module named yaml
> 
> Try manually building your Python code by running: $ python setup.py sdist and providing the output via the `--packages` flag (for example, `--pac



I am not a R programmer, but would like to evaluate the same from RStudio. What do you need other than train.R on your computer to test it? Can anyone share a sample train.R and any associated files for the test?
