### ISSUE TITLE
gs_rsync creates a local directory when destination is google storage

### ISSUE THREAD

**Issue by zamorarr** [rstudio/cloudml#172]
When using `gs_rsync` to upload a local source folder to a cloud destination folder, an empty local directory is created with the name of the cloud folder. 

**Reproducible Example**
```R
# local source data to upload
dir.create("tmp")
file.create("tmp/hello.txt")

# cloud destination
mybucket <- "gs://your-bucket-here"
gs_rsync("tmp", mybucket)

# now there is a nested local directory at gs:/<mybucket> !
utils::file_test("-d", mybucket)
```

**Error Location**
The error is coming from [this line](https://github.com/rstudio/cloudml/blob/4ea534ae08a67763bf2714292146d3bab47d9a6e/R/gcloud-storage.R#L70)

```R
 if (!utils::file_test("-d", destination))
    dir.create(destination, recursive = TRUE)
```

**Proposed Solution**
I believe a simple fix would be to test if the destination is a Google Storage URI. 

```R
  if (!is_gs_uri(destination) & !utils::file_test("-d", destination)) {
    dir.create(destination, recursive = TRUE)
  }
```

I can submit a PR if needed. Thanks!

**Comment by javierluraschi** [comment]
Thank you, @zamorarr, fixing with https://github.com/rstudio/cloudml/pull/173! PR's are always welcomed, thanks for considering sending one our way!
