### ISSUE TITLE
mechanism for caching packages?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#18]
During deployments, a very large amount of time is spent installing package dependencies from CRAN and GitHub. We should figure out a way to offset this cost.

## Preloaded Images

We could get in touch with the Google folks, and ask them to pre-bake the TensorFlow images that get launched with `ml-engine` with a set of R packages (`tidyverse` + `tensorflow` + `tfruns` + `cloudml`).

## Packrat Cache

When developers opt-in to using Packrat, we could enable the use of the Packrat cache. The packages would need to get cached on to a persistent filesystem. Some potential ways forward:

- Use FUSE to mount the bucket as an actual filesystem path, and tell Packrat to use that: https://cloud.google.com/storage/docs/gcs-fuse

- Manually use `gsutil` to copy the library path from the bucket to the local instance's filesystem, and use that.

**Comment by jjallaire** [comment]
Google seemed open to the idea of pre-baking R + package into some flavor of their cloudml images, let's hope this materializes!

**Comment by javierluraschi** [comment]
Implemented now using `packrat`.
