### ISSUE TITLE
cloud_init() fails on Rstudio server

### ISSUE THREAD

**Issue by yunching** [rstudio/cloudml#191]
Hi,

Is it possible to get the cloudml library working on Rstudio server? It seems like the lack of a browser is causing the below error message when cloud_init() runs:

xdg-open: no method available for opening 'https://accounts.google.com/o/oauth2/auth?redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&access_type=offline'

Thanks!

**Comment by mkirby3** [comment]
I had the same issue.

You can run the following directly from the RStudio Server terminal:
`gcloud auth login --no-launch-browser`

Then just copy and paste the verification code from your browser into the RStudio Server terminal.

Hope that helps.

**Comment by yunching** [comment]
This works like a charm. Thanks!

**Comment by markbneal** [comment]
Worked for me. Given name change for Server, I'm adding RStudio Workbench xdg-open: no method available for opening in this comment so it comes up in search results.
