### ISSUE TITLE
avoid duplication of data retrieved from gs:// URLs

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#20]
We currently use the `gs_data` function for synchronization of data from Google Storage URLs to local paths. By default, we download these to a local path `gs`.

Because that `gs` directory ends up in the run directory, we end up synchronizing data to the bucket. This could be wasteful (we end up duplicating data in the bucket across multiple directories for each run).

**Comment by jjallaire** [comment]
I think we should drop the whole gs_data thing (I think it's premature
optimization and as a result adds needless complexity)

**Comment by kevinushey** [comment]
Don't we still need this (or something like this) for synchronization of files contained in Google Cloud storage with the instance doing the training? How do we want launched instances to access data contained in Google Cloud storage?

**Comment by jjallaire** [comment]
I think you can pass gs:// URLs directly to data ingest functions. I
believe the only reason we did gs_data was to make it easy to centrally
distribute local test/dev data, but there are other ways to do that.

Let's discuss realtime tomorrow

**Comment by kevinushey** [comment]
I know TensorFlow APIs tend to accept `gs://` URLs directly, but the APIs we're providing on top (e.g. with `tfestimators`) don't.

More generally (in the context of e.g. `tfestimators`), I'm not sure how we should define an input function that receives data from a dataset stored on Google Cloud storage. Are there facilities for handling this in the `keras` package?

**Comment by jjallaire** [comment]
I believe that tfdatasets will support gs://

For Keras we should use the get_file function but perhaps that won't work
with authenticated URLs?

**Comment by jjallaire** [comment]
gs issue fixed, we will address gs:// with a separate feature soon!
