### ISSUE TITLE
Is this package still NSFW?

### ISSUE THREAD

**Issue by page1** [rstudio/cloudml#23]
This looks like a very interesting package, but readme is foreboding.

I'm working with rstudio/keras and loving it. If this can easily let me send my models to google for training that would be great. 

Looking over the docs I'm a bit confused because I figured `cloudml_train` was going to be the function to work with, but the examples are devoid of calling that function.

If this is working I'm willing to invest in learning to use it.

**Comment by jjallaire** [comment]
We've been on and off on development here but we are committed to delivering a fully tested and documented release over the next couple of months.

In the meantime, I believe that things should still be in working order. @kevinushey Could you write up quick revised README for motivated users that outlines the basic workflow? 

@page1 Once you get things working please let us know what issues you encounter and we will address them ASAP.

**Comment by page1** [comment]
Thanks. It would be great if there was a hello world taking you from 
```
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 10, activation = 'relu', input_shape = ncol(x_train)
model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = optimizer_adam(),
  metrics = c('acc', 'mse')
)
```
to a `cloudml_train` function that operated similarly to keras `fit`

If that was working that would make on boarding really easy for anyone using the Rstudio verison of keras.

Does the google ML training return the trained model? Or do you have to use google for prediction if you train it with their tools? Right now I'm just exploring and won't need the high prediction speed of a managed service, but I could use help with training horse power.

**Comment by jjallaire** [comment]
No, when you do a training job you simply "collect" the output directory of your training to the local system (it's as if you had done all the work locally). So you would add `save_model_hdf5()` to your script and then you'll have the saved model locally when training is done.

**Comment by kevinushey** [comment]
I've updated the [README](https://github.com/rstudio/cloudml/blob/master/README.md) to give a bit more description of the prescribed workflow. Right now, it should be possible to submit a model for training on Google Cloud.

Note that currently, the training process is somewhat slow as each launched instance needs to provision an R environment + the required TensorFlow + Keras packages used for training. Currently, only TensorFlow v1.2 is supported on Google Cloud ML; they're planning to upgrade to support TensorFlow v1.4 in the near future.

Some more work is still required on our end to support the various prediction APIs, though, but it should at least be possible to train a TensorFlow model on Google Cloud, and then collect the trained model outputs locally.

We would definitely welcome some feedback if you want to try using the package and happen to run into any road blocks along the way!
