### ISSUE TITLE
Model Checkpoints - Missing h5py

### ISSUE THREAD

**Issue by page1** [rstudio/cloudml#26]
Any suggestions how to save model checkpoints? I've got the following callback:
```
best_model_save <- callback_model_checkpoint(best_model_file_local, save_best_only = T)
```
But it gives me:
```
The h5py Python package is required to save model checkpoints
```
Is the h5py not installed with keras?

Another question: Should the checkpoints be written to a local file and then copied to GCS, or is it possible to send them direct to cloud storage? I'm assuming this same process of write to local disk and then copy to GCS is needed to fetch the final model?

**Comment by jjallaire** [comment]
Thanks for all of the reports! I'm afraid you are a couple of weeks ahead of us here so some of these issues might not get resolved right away. We'll be back at this soon and will ping you back on these threads once we are.

**Comment by page1** [comment]
np 👍

**Comment by jjallaire** [comment]
Fixed, we now preinstall keras and all of it's dependencies
