### ISSUE TITLE
Warning: TensorFlow library wasn't compiled to use SSE4.1

### ISSUE THREAD

**Issue by page1** [rstudio/cloudml#28]
Model is giving me this warning:
```
 W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
```
Just a detail at this point. No biggy

**Comment by page1** [comment]
Same alert for the following:
- SSE4.2
- AVX
- AVX2
- FMA

**Comment by jjallaire** [comment]
Hopefully at some point the CloudML instances will have a custom compiled version of TF which picks up these optimizations. In the meantime hopefully it won't matter because they all have GPUs!

**Comment by page1** [comment]
The instances don't ship with precompiled TF 😱 ?

**Comment by kevinushey** [comment]
They ship with TF, but it's an older version (1.2) which is not supported by any of our R package infrastructure. Our workaround for testing is to just install the latest version using `pip`, but that provides the user with a version compiled with minimal support for newer processor instructions.
