### ISSUE TITLE
job fails to submit when containing directory includes a dash

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#42]
I had a directory with a dash in it (hello-cloudml) and got this error:

```
ERROR: (gcloud.ml-engine.jobs.submit.training) INVALID_ARGUMENT: Field: job_id Error: A name should start with a letter and contain only letters, numbers and underscores.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: A name should start with a letter and contain only letters, numbers
      and underscores.
    field: job_id
```

Renaming the directory to `hello_cloudml` resolved the error. Perhaps we need to substitute invalid characters somewhere in the submission pipeline?

**Comment by jjallaire** [comment]
Trining to make the local directory name align with the project name however project names can’t include _ in them. So right now the only way to have the local directory and the project name be the same is to include neither - nor _ (e.g. “hellocloudml”)

**Comment by hafizurcse** [comment]
In my case, the job name was the issue. Google makes an issue if you have dash (-) in your job name. 

For example, following were not working and producing an error as reported by @jjallaire:
```PROJ_NAME="my-first-project"
JOB_NAME=$PROJ_NAME"_$(date +%Y%m%d_%H%M%S)"```

Then I replaced by:
```PROJ_NAME="my_first_project"
JOB_NAME=$PROJ_NAME"_$(date +%Y%m%d_%H%M%S)"```

and it works fine.

**Comment by sohartma** [comment]
> 
> 
> In my case, the job name was the issue. Google makes an issue if you have dash (-) in your job name.
> 
> For example, following were not working and producing an error as reported by @jjallaire:
> 
> ```
> PROJ_NAME="my-first-project"
> JOB_NAME=$PROJ_NAME"_$(date +%Y%m%d_%H%M%S)"
> ```
> 
> Then I replaced by:
> 
> ```
> PROJ_NAME="my_first_project"
> JOB_NAME=$PROJ_NAME"_$(date +%Y%m%d_%H%M%S)"
> ```
> 
> and it works fine.

Hi, i'm having the same issue. Where exactly did you rename your project and job names? I renamed my project in the google cloud, that doesn't help. I renamed my job in the command i run in the terminal, that doesn't help either...
