### ISSUE TITLE
revamped specification of configuration info

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#56]
@javierluraschi and I discussed this:

1) Leave flags as-is

2) Remove `config` option (which is currently defaulted to "cloudml") since we think it's unlikely anyone will ever want a different named config (this is for named profiles in flags)

3) The "config" option will now point to a standard CloudML config file (JSON or YAML): https://cloud.google.com/ml-engine/reference/rest/v1/projects.jobs which can be used to set scaleTier, region, etc. etc. This means that our special config.yml file goes away in preference to the standard google format.

4) Specifying `account` and `project` parameters different than the user's global default will be done in an optional `gcloud.yml` file.

So we'd have:

flags.yml (optional flag overrides for cloudml training, etc.)
cloudml.yml (Google CloudML config)
gcloud.yml (override of account and/or project)

**Comment by jjallaire** [comment]
See also #11  and #16

**Comment by jjallaire** [comment]
Re-opening to address requirement of `gcloud` parameter on all functions that interact with gcloud

**Comment by javierluraschi** [comment]
https://github.com/rstudio/cloudml/pull/81 takes care of this, merging once travis succeeds.
