### ISSUE TITLE
Any plans for JSON API implementation?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/cloudml#6]
Very excited to see this project at Next today :)

I was just wondering if you are planning to implement via the JSON API too? https://cloud.google.com/ml-engine/reference/rest/

**Comment by jjallaire** [comment]
We're currently calling the local Google Cloud SDK. One benefit of this is that the SDK handles authentication as well as other vagaries of the REST interface. It also provides some classes for local training and prediction for dry runs.

Given these benefits, what would be a good reason for us to consider using the JSON API? (instead of or as well as the SDK binary). One reason I can think of is ease of installation, but it feels like an awful lot of work for us to avoid a local install that the user might well need to do anyway (e.g. for moving data back and forth to google storage).

**Comment by MarkEdmondson1234** [comment]
I guess the only reason is to avoid the gcloud/python dependency, but as you say users must have at least installed Tensorflow so it is perhaps not a strong enough reason.  :)

The auth and google cloud storage is something I've dealt with before, I have for example a rest API implementation of [google storage](https://github.com/cloudyr/googleCloudStorageR).  

Thinking about it, using gcloud does mean Shiny app authentication for an end user would be more difficult without a reactive auth token calling a python auth flow, so no multi-user Shiny apps using the user's own credentials, but not a common scenario.  I would though be happy to offer a pull request if you thought it worth pursuing. 

I guess I'm looking at how cloudml could integrate with my current workflow.  Switching that around what use cases would using the R library over just calling the gcloud client?  Currently I'm even using an Rmd file to call the python. [(example)](https://rpubs.com/MarkeD/datalab).

**Comment by jjallaire** [comment]
The R library will be higher level (typically one simple function call vs. a command line invocation with multiple arguments) and will take advantage of convention/configuration that we setup for cloudml projects. 

If we could wave a magic want I completely agree that users not having to install the GCloud SDK would be wonderful. For bootstrapping this project though we don't want to go there right now.

**Comment by MarkEdmondson1234** [comment]
Cool, makes sense, I'll perhaps try a fork of it once you have a first release.

**Comment by jjallaire** [comment]
We're still actively considering whether to switch to the JSON API (will update this thread once we make a final decision).

**Comment by MarkEdmondson1234** [comment]
I thought of two more reasons, from when I first tried wrapping `gcloud` tool myself (for a very early bigquery tool) - cross platform compatibility issues (windows vs osx) (lowercase vs uppercase vs spaces in filenames, quoting of shell etc.) and an issue then was when errors were in the gcloud tool it would sometimes crash RStudio instead of being able to be halted.  Perhaps this is fixed now though.

**Comment by jjallaire** [comment]
No, the commands are still uninterruptible (which is indeed a huge problem).
