### ISSUE TITLE
clean out staging bucket?

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#63]
I noticed that we leave a bunch of our staging packages in the staging bucket:

<img width="1255" alt="screen shot 2017-12-12 at 9 40 46 am" src="https://user-images.githubusercontent.com/104391/33890250-ab610208-df20-11e7-8e4b-851136a56065.png">

Should these be removed after the job completes?

**Comment by javierluraschi** [comment]
I would argue that since this is created with `cloudml` using `--job-dir`, it should be cloudml the one cleaning it. That said, in a few narrow cases, the original package is useful for troubleshooting failed runs.

**Comment by jjallaire** [comment]
Okay, let’s leave this as-is then
