### ISSUE TITLE
consider new scheme for job directories

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#7]
We currently have the `job_dir` option which defaults to `jobs/local` when running locally and defaults to `!expr cloudml::unique_job_dir("gs://example/jobs")` when running on Cloud ML. The default behavior uses a single `job_dir` for the local case (so that local testing just overwrites previous testing) and multiple job directories on Cloud ML.

We might consider a new scheme that is simpler to specify in the config file and brings some consistency with job names. While `job_dir` would always be available as an explicit override, in the new scheme we'd by default construct the job directory from the combination of a `job_output` key and the job's name. The config file for this might look as follows:

```yaml
default:
   project_name: census-demo
   job_output: jobs/local

cloudml:
   job_output: gs://bucket-name/census-demo/jobs
```

We'd automatically generate a `job_name` based on the `project_name` and the current date/time stamp (we do this now but use the directory name rather than an explicit project name). The default `job_dir` would then be `job_output/job_name`. A side benefit of this scheme would be that the `job_name` and the directory containing the job output would be the same (it's different now which is a bit confusing).

By default local jobs wouldn't have a `job_name` and therefore would only save one job output at a time. We'd also replace the current `unique_job_dir` function with a `unique_job_name` function.

@kevinushey What do you think?

@terrytangyuan Let us know if there are perspectives we are missing in reasoning about this.

**Comment by terrytangyuan** [comment]
Just want to make sure I understand this correctly, the default `job_dir` is going to be `job_output/project_name/timestamp`. I think it's very necessary to create a scheme for this and timestamped dir names are very useful, e.g. so users can write script to compare model performance.

**Comment by terrytangyuan** [comment]
Would users create multiple jobs in parallel? Timestamp might not be unique + same project_name might cause some issues.

**Comment by jjallaire** [comment]
We were thinking it would be `job_output`/`project_name-timestamp` since the job output directories are presumably already scoped to project. This would also allow the job_dir to be identical to the job_name which will be a more clear and transparent schema I think.

They could create multiple jobs in parallel but these jobs are created by executing code within an R session and the timestamp goes down to the microsecond. Unlikely to be a conflict but we should probably throw some additional randomness in there for good measure.

**Comment by terrytangyuan** [comment]
Yeah some randomness is always good. `job_output/project_name-timestamp` sounds good. Also I think it might be good to allow users to specify an identifier. For example, they want to see instinct comparisons between `model_with_featureA` and `model_with_featureB` without iterating through each timestamped folder to find some metadata.

**Comment by jjallaire** [comment]
We could have a `job_name` function which would accept the identifier and
create a complete name based on the current project, identifier, and a
timestamp (with the default being to just use the project name and
identifier).

**Comment by kevinushey** [comment]
I like this scheme quite a bit as well. We should also allow users to just specify a `job_dir` explicitly (if that's what they prefer), but I think this will overall be much nicer.

**Comment by jjallaire** [comment]
I think that once we have a `project_name` that accurately reflects the Google Cloud project name we can also add a `project_bucket` setting that represents the default root bucket for the project (this can default to `gs://<project_name>` if and only if this is a very common convention). We can then default `job_output` to `project_bucket/jobs`.

**Comment by jjallaire** [comment]
Note that we will ultimately be required to have the Google Cloud `project_name` because all of our commands (whether delivered via the command line tools or the REST API) will need to be scoped by project.

**Comment by kevinushey** [comment]
I'm going to close this issue for now -- most of the discussion here is covered in the separate issues, and I think the `jobs` directory bits will be superceded by the use of `tfruns`.
