### ISSUE TITLE
does job_download handle multiple trials gracefully?

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#75]
I noticed that `job_download` masks out `trials = "all"` but what about if multiple trial ids are specified?

**Comment by javierluraschi** [comment]
That also works fine for `job_collect()`, `job_download()` is an internal function that only handles a single trial, so running:

```r
job_collect("cloudml_2017_12_13_012055742", trials = c(1,2))
```

collects both trials correctly for me:

<img width="477" alt="screen shot 2017-12-13 at 9 27 23 am" src="https://user-images.githubusercontent.com/3478847/33952841-dbea3e18-dfe7-11e7-84a3-65b5e1a34e75.png">

Feel free to reopen if you experience something different than this.

**Comment by jjallaire** [comment]
Okay, glad we are doing this. One thing we should change though is that all runs should be downloaded to the root directory (so that tfruns picks them all up in e.g. ls_runs(). Let's maybe add an e.g. `-1`, `-2` suffix to the job id and download them all to the root (it should probably use however many digits are required to have the runs show up in order -- for example if there are 500 runs then the suffix should be `-001`, `-002`, etc.

**Comment by javierluraschi** [comment]
Fixed with https://github.com/rstudio/cloudml/pull/83.
