### ISSUE TITLE
job data is only partially written in tfruns

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#84]
As of the last few commits the data written within tfruns is now incomplete, so attempting to view the run fails with this error:

```{r}
Error in basename(run$script) : a character vector argument expected
Calls: <Anonymous> ... job_download -> <Anonymous> -> run_view_data -> basename
In addition: Warning message:
In max(job_list_trials(job)) :
  no non-missing arguments to max; returning -Inf
Execution halted
```

You can repro this with any job that you submit fresh.

At first glance it looks like maybe the deploy.rds file doesn't have the `entrypoint` field? 

Are there any changes you can think of that would have caused this? I guess worst case we can git bisect.

**Comment by jjallaire** [comment]
Everything works fine in this commit so that's a basic for git bisect: https://github.com/rstudio/cloudml/commit/360b5b7f116e701201ceeb78d38429cdb4162cd2

**Comment by jjallaire** [comment]
It's the most recent commit that caused the regression: https://github.com/rstudio/cloudml/pull/83/commits/1eb71598a5311c9566b80d184b1173808494d92f

I'll revert for now.

**Comment by jjallaire** [comment]
This update to the tests should ensure that they fail for this regression: https://github.com/rstudio/cloudml/commit/8e0ce418984754b6aeb513ae445339c62ab3c122

**Comment by javierluraschi** [comment]
Thanks, hopefully this is all fixed with https://github.com/rstudio/cloudml/pull/85; otherwise, let me knwo!
