### ISSUE TITLE
error during cloudml_predict

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#90]
I'm attempting to test the hello world deploy/predict workflow from the vignette and I get this error:

<img width="829" alt="screen shot 2018-01-03 at 8 07 49 am" src="https://user-images.githubusercontent.com/104391/34521785-9345de98-f05d-11e7-9e73-19466ea520eb.png">

Note that I've made some minor changes (requiring the `name` parameter) but I don't think this has anything to do with the error.

**Comment by javierluraschi** [comment]
@jjallaire this one is working fine for me, I retrained, redeployed a model following the deployment guide and got as output:

```r
> cloudml_predict(
+     name = "hello_world",
+     list(
+         list(name = "cloudml"),
+         list(name = "tensorflow")
+     )
+ )
$predictions
               hello
1    Hello, cloudml!
2 Hello, tensorflow!
```

However, there have been a few fixes in `export_savedmodel()`, I'm on `tensorflow_1.4.3.9000`, are you perhaps in the CRAN version?

**Comment by jjallaire** [comment]
Okay, I am now seeing this run without errors!

One curious thing is now the predications are displayed in the notebook:

<img width="830" alt="screen shot 2018-01-04 at 7 52 17 am" src="https://user-images.githubusercontent.com/104391/34564347-4c3dcba6-f124-11e7-8031-9c87ce0c2c7d.png">

Is there a way to make that display more straightforward?

**Comment by javierluraschi** [comment]
Yeah, we can fix the formatting for sure.
