### ISSUE TITLE
remove gcloud config options from R functions

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#94]
In testing the gcloud config options I realized that the gsutil command line utility works only with the currently active Google Cloud SDK account and project. Since we rely on calling gsutil to probe for and automatically create a project storage bucket, I think this implies that we can also only support the currently active account and project.

So I think we should remove all of the gcloud arguments and instead just rely on the currently active default account, project, and region.

**Comment by javierluraschi** [comment]
While reproeing some of the recent github issues, I had to change region since we defaulted to `us-east1` but I'm not whitelisted to use that one. So I had to run instead:

```
> cloudml_deploy(model_dir, name = "hello_world", gcloud = list(region = "us-central1"))
Model created and available in https://console.cloud.google.com/mlengine/models/hello_world
```

which worked as expected. Investigating a bit further for account and project...

**Comment by jjallaire** [comment]
The issue is that the new P100 GPU instances (which are currently in beta) are only available in some regions. It would be good if our default was one of these regions.

**Comment by javierluraschi** [comment]
I've used `P100 GPU` in the `us-central1` region, as in:

```r
setwd("inst/examples/mnist")
cloudml_train(master_type = "standard_p100")
```

<img width="510" alt="screen shot 2018-01-03 at 10 54 20 am" src="https://user-images.githubusercontent.com/3478847/34534818-7c1a291a-f074-11e7-8b22-51a44fa891c2.png">

Maybe they got added recently?

**Comment by javierluraschi** [comment]
Seems like we can also consider supporting switching accounts when needed, see: https://github.com/rstudio/cloudml/pull/98

I validated by deploying across accounts:

```
cloudml_deploy(
  "savedmodel",
  name = "javier_mnist",
  gcloud = list(
      account = "name@gmail.com",
      project = "javier-cloudml",
      region = "us-central1"
  )
)
```

and

```
cloudml_deploy(
  "savedmodel",
  name = "javier_mnist",
  gcloud = list(
      account = "name@rstudio.com",
      project = "javier-cloudml",
      region = "us-central1"
  )
)
```
